version: 0.1.0                                            # stack schema version 0.1.0 (latest)

name: Deploy a NextJS based site to Github Pages              # stack name 
description: Deploy a NextJS based site to Github Pages       # stack description

branding:                                              # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                # stack inputs 
    
  - name: NODE_VERSION                                 # stack input name
    default: v12.22.4                              # stack input default value provided
    description: NODE_VERSION for nodejs stack         # stack input description
    validvalues:                                       # stack input valid values that can be selected
    - v12.22.4
    - v14.17.4
    
  - name: GITHUB_PAT
    description: GitHub PAT with repo and workflow permissions
    is-secret: true
    required: true

configs:                                               # stack config applied to new repository
  repo-metadata:
     parameters:
       description: 'Setup your Nextjs site in Github Pages'
       secrets: 
         - name: GH_PAT
           value: ${{inputs.GITHUB_PAT}}
       topics:                                            # repository tags for new repository
       - nextjs
       - github-pages

  branches:                                            # branching configs for new repository
    - name: main
      parameters:
        dismiss-stale-reviews: true                      # default: false
        required-approving-review-count: 1
        require-code-owner-reviews: true

  environments:                                        
    - name: development
      parameters: 
        protected-branches: false
        custom-branch-policies:
          - main
          - releases/*

init:
 uses: ".github/workflows/stack-init.yaml"
